### ISSUE TITLE
Investigate Use of GitHub URL for docker-compose version 2

### ISSUE THREAD

**Issue by kevingurney** [Molecular-Playground/molecular-playground#5]
Investigate Use of GitHub URL for docker-compose version 2.

**Comment by stanleyrya** [comment]
Let's do this one tomorrow @kevingurney :)

And by that I mean look into it tomorrow and take care of this issue.

**Comment by stanleyrya** [comment]
ok, lets look into this today haha

**Comment by akaplo** [comment]
Closed cause #wontfix
