### ISSUE TITLE
Cross-Origin Resource Sharing (CORS) Issues

### ISSUE THREAD

**Issue by GaryPWhite** [Molecular-Playground/molecular-playground#8]
The backend should accept [preflight](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests) requests that are being made from the frontend. The best approach is guess-and-check with the things that bring errors up from a frontend console, but I'm sure there is a list of general usage.

For now, I know this:
for the OPTIONS HTTP verb, be sure to allow certain parameters with the response sent from the server. Some of those headers are:
"Access-Control-Allow-Version" : "*",
something about content-type
something about data, I THINK. Not sure it has to be handled.

Sorry about the vagueness.

**Comment by stanleyrya** [comment]
Fixed in https://github.com/molecular-playground/gateway/commit/6caf5aaf856a9b097993171374f4488c24a2b22e
